# Generated by Django 5.2.3 on 2025-06-18 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_in', models.TimeField(verbose_name='Time In')),
                ('time_out', models.TimeField(verbose_name='Time Out')),
                ('total_duration', models.DurationField(verbose_name='Total Duration')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Study Record',
                'verbose_name_plural': 'Study Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Tam', 'Tamil'), ('Eng', 'English'), ('Math', 'Mathematics'), ('Sci', 'Science'), ('SS', 'Social Studies'), ('Comp', 'Computer Science'), ('Other', 'Other')], max_length=100, verbose_name='Subject')),
                ('time_spent', models.DurationField(verbose_name='Time Spent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.studyrecordmodel')),
            ],
            options={
                'verbose_name': 'Subject Record',
                'verbose_name_plural': 'Subject Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
