# Generated by Django 5.2.3 on 2025-06-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_staffmodel_students_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecordmodel',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.studentmodel', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studyrecordmodel',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.staffmodel', verbose_name='Staff Name'),
        ),
    ]
