# Generated by Django 5.2.3 on 2025-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrecordmodel',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Study Record', 'verbose_name_plural': 'Study Records'},
        ),
        migrations.AlterField(
            model_name='studyrecordmodel',
            name='total_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Total Duration'),
        ),
    ]
