# Generated by Django 5.2.3 on 2025-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_studyrecordmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecordmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
