# Generated by Django 5.2.3 on 2025-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_subjectrecordmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecordmodel',
            name='other_qn',
            field=models.IntegerField(default=0, verbose_name='Other Learned'),
        ),
        migrations.AddField(
            model_name='subjectrecordmodel',
            name='total_2_mark',
            field=models.IntegerField(default=0, verbose_name='Total 2 Mark Questions Learned'),
        ),
        migrations.AddField(
            model_name='subjectrecordmodel',
            name='total_5_mark',
            field=models.IntegerField(default=0, verbose_name='Total 2 Mark Questions Learned'),
        ),
    ]
