# Generated by Django 5.2.3 on 2025-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_studyrecordmodel_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='passCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pass Code'),
        ),
    ]
